# Generated by Django 4.1.7 on 2023-03-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0008_warningprofiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPhone11ProfileData',
            fields=[
                ('profile_idx', models.AutoField(primary_key=True, serialize=False)),
                ('profile_count', models.IntegerField(default='-1')),
                ('device_name', models.CharField(default='none', max_length=100)),
                ('project_name', models.CharField(default='none', max_length=100)),
                ('scene_name', models.CharField(default='none', max_length=100)),
                ('date', models.CharField(max_length=500)),
                ('fps', models.FloatField(default=0.0)),
                ('min_fps', models.FloatField(default=0.0)),
                ('avg_fps', models.FloatField(default=0.0)),
                ('max_fps', models.FloatField(default=0.0)),
                ('set_pass_call', models.FloatField(default=0.0)),
                ('draw_call', models.FloatField(default=0.0)),
                ('tris', models.FloatField(default=0.0)),
                ('vertices', models.FloatField(default=0.0)),
                ('total_memory', models.FloatField(default=0.0)),
                ('system_memory', models.FloatField(default=0.0)),
                ('texture_memory', models.FloatField(default=0.0)),
                ('mesh_memory', models.FloatField(default=0.0)),
            ],
        ),
    ]
