# Generated by Django 4.1.7 on 2023-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0009_iphone11profiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioDataTable',
            fields=[
                ('scenario_data_idx', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('scenario_data_subject', models.CharField(max_length=500)),
                ('scenario_data_text', models.TextField()),
                ('scenario_data_file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
    ]
