# Generated by Django 4.1.7 on 2023-03-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0011_scenariodatatable_scenario_profile_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariodatatable',
            name='device_name',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
