# Generated by Django 4.1.7 on 2023-03-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0012_scenariodatatable_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfoTable',
            fields=[
                ('device_info_idx', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='none', max_length=30)),
                ('device_profile_name', models.CharField(default='none', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfoTable',
            fields=[
                ('project_info_idx', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='none', max_length=30)),
            ],
        ),
    ]
