# Generated by Django 4.1.7 on 2023-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0013_deviceinfotable_projectinfotable'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariodatatable',
            name='ordering_number',
            field=models.IntegerField(default=0),
        ),
    ]
