# Generated by Django 4.1.7 on 2023-03-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0014_scenariodatatable_ordering_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariodatatable',
            options={'ordering': ['-ordering_number']},
        ),
    ]
