# Generated by Django 4.1.7 on 2023-03-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0016_alter_scenariodatatable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileResultTable',
            fields=[
                ('profile_result_idx', models.AutoField(primary_key=True, serialize=False)),
                ('device_temperature', models.FloatField(default=0.0)),
                ('ordering_number', models.IntegerField(default=0)),
                ('scenario_profile_idx', models.IntegerField(default=0)),
                ('device_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unityprofile.deviceinfotable')),
                ('scenario_data_subject_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unityprofile.scenariodatatable')),
            ],
        ),
    ]
