# Generated by Django 4.1.7 on 2023-03-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0017_profileresulttable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileresulttable',
            options={'ordering': ['ordering_number']},
        ),
    ]
