# Generated by Django 4.1.7 on 2023-03-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0018_alter_profileresulttable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileresulttable',
            name='project_name',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
