# Generated by Django 4.1.7 on 2023-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0021_rename_profile_result_idx_profileresulttable_profile_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileresulttable',
            name='target_fps',
            field=models.IntegerField(default=30),
        ),
    ]
