# Generated by Django 4.1.7 on 2023-03-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0022_profileresulttable_target_fps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfotable',
            name='device_name',
            field=models.CharField(default='none', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profileresulttable',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unityprofile.deviceinfotable'),
        ),
    ]
