# Generated by Django 4.0.6 on 2022-07-18 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfoTable',
            fields=[
                ('map_info_idx', models.AutoField(primary_key=True, serialize=False)),
                ('map_info_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MapDataTable',
            fields=[
                ('map_data_idx', models.AutoField(primary_key=True, serialize=False)),
                ('map_data_subject', models.CharField(max_length=500)),
                ('map_data_text', models.TextField()),
                ('map_data_file', models.CharField(max_length=500, null=True)),
                ('map_data_date', models.DateTimeField()),
                ('map_data_writer_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.usertable')),
                ('map_info_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.mapinfotable')),
            ],
        ),
    ]
