# Generated by Django 4.0.6 on 2022-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdatatable',
            name='map_data_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
